stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage02_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage02_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/cnnClassifier/pipeline/stage03_modelTraining.py
    deps:
      - src/cnnClassifier/pipeline/stage03_modelTraining.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGEMENTATION
    outs:
      - artifacts/training/model.keras


  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage04_model_evluaton.py
    deps:
      - src/cnnClassifier/pipeline/stage04_model_evluaton.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false